import React, { useRef, useState } from 'react';
import html2canvas from 'html2canvas';
import { Download, Share2, Trophy } from 'lucide-react';

export default function WorkoutShareCard({ workout }) {
  const cardRef = useRef(null); const [busy, setBusy] = useState(false);
  const generate = async () => { setBusy(true); try { const canvas = await html2canvas(cardRef.current, { backgroundColor: '#090909', scale: 2 }); return await new Promise((resolve) => canvas.toBlob(resolve, 'image/png')); } finally { setBusy(false); } };
  const share = async () => { const blob = await generate(); if (!blob) return; const file = new File([blob], 'grindx-workout.png', { type: 'image/png' }); if (navigator.canShare?.({ files: [file] })) await navigator.share({ title: workout.title, text: 'My GRIND-X workout', files: [file] }); else { const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = file.name; anchor.click(); URL.revokeObjectURL(url); } };
  return <section className="space-y-3"><div ref={cardRef} className="theme-dark-surface overflow-hidden rounded-3xl border border-red-500/30 bg-gradient-to-br from-red-950 via-neutral-950 to-black p-6 text-white"><div className="flex justify-between"><span className="font-black tracking-[.18em] text-red-400">GRIND-X</span><Trophy className="text-yellow-400" /></div><h2 className="mt-8 text-3xl font-black">{workout.title}</h2><p className="text-sm text-neutral-400">{new Date(workout.completedAt || workout.date).toLocaleDateString()}</p><div className="mt-6 grid grid-cols-3 gap-2"><Metric label="Exercises" value={workout.exercises?.length || 0} /><Metric label="Volume" value={`${workout.totalVolume || 0}kg`} /><Metric label="Duration" value={`${Math.round((workout.duration || 0) / 60)}m`} /></div><div className="mt-5 flex flex-wrap gap-2">{workout.exercises?.slice(0, 6).map((exercise) => <span key={exercise.exerciseName} className="rounded-full bg-white/10 px-2.5 py-1 text-xs">{exercise.exerciseName}</span>)}</div></div><button onClick={share} disabled={busy} className="flex w-full items-center justify-center gap-2 rounded-xl bg-red-600 py-3 text-sm font-black text-white">{navigator.share ? <Share2 size={17} /> : <Download size={17} />}{busy ? 'Generating…' : 'Share workout card'}</button></section>;
}
function Metric({ label, value }) { return <div className="rounded-xl bg-white/5 p-3"><p className="text-[9px] uppercase text-neutral-400">{label}</p><p className="font-black">{value}</p></div>; }
