import React, { useEffect, useRef, useState } from 'react';
import { motion } from 'framer-motion';
import { CalendarDays, Clock, Dumbbell } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import api from '../utils/api';
import { getMuscleGroup } from '../utils/muscleGroupHelper';

export default function WorkoutTimeline() {
  const navigate = useNavigate(); const [items, setItems] = useState([]); const [page, setPage] = useState(1); const [hasMore, setHasMore] = useState(true); const [loading, setLoading] = useState(false); const sentinel = useRef(null);
  useEffect(() => { let active = true; setLoading(true); api.get('/workouts', { params: { page, limit: 10 } }).then(({ data }) => { if (!active) return; setItems((current) => page === 1 ? data.workouts || [] : [...current, ...(data.workouts || [])]); setHasMore(Boolean(data.pagination?.hasMore)); }).finally(() => active && setLoading(false)); return () => { active = false; }; }, [page]);
  useEffect(() => { const observer = new IntersectionObserver(([entry]) => { if (entry.isIntersecting && hasMore && !loading) setPage((value) => value + 1); }, { rootMargin: '240px' }); if (sentinel.current) observer.observe(sentinel.current); return () => observer.disconnect(); }, [hasMore, loading]);
  return <div className="relative mx-auto max-w-5xl"><div className="absolute bottom-0 left-5 top-0 w-px bg-gradient-to-b from-red-500 via-orange-500 to-transparent md:left-1/2" />{items.map((workout, index) => { const muscle = workout.muscle || workout.category || getMuscleGroup(workout.title); return <motion.article key={workout._id} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: (index % 10) * .04 }} className={`relative mb-6 ml-12 md:ml-0 md:w-[calc(50%-2rem)] ${index % 2 ? 'md:ml-auto' : ''}`}><span className={`absolute top-6 h-4 w-4 rounded-full border-4 border-black bg-red-500 ${index % 2 ? '-left-10 md:-left-[2.55rem]' : '-left-10 md:-right-[2.55rem]'}`} /><button onClick={() => navigate(`/workout-details/${workout._id}`, { state: { workout } })} className="w-full rounded-2xl border border-neutral-800 bg-neutral-900 p-5 text-left shadow-xl transition hover:border-red-500/40"><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-xs text-neutral-400"><CalendarDays size={14} />{new Date(workout.date).toLocaleDateString()}</span><span className="rounded-full bg-red-500/10 px-2 py-1 text-[10px] font-black text-red-400">{muscle}</span></div><h2 className="mt-3 text-lg font-black text-white">{workout.title}</h2><div className="mt-3 flex gap-4 text-xs text-neutral-400"><span className="flex items-center gap-1"><Clock size={13} />{workout.durationMinutes || 0} min</span><span className="flex items-center gap-1"><Dumbbell size={13} />{workout.totalVolume || 0} kg</span></div></button></motion.article>; })}<div ref={sentinel} className="py-6 text-center text-sm text-neutral-500">{loading ? 'Loading sessions…' : hasMore ? 'Scroll for more' : 'You reached the beginning of your journey.'}</div></div>;
}
